name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code and Build on Server
        run: |
          ssh -o StrictHostKeyChecking=no f4host@${{ secrets.STAGING_SERVER_IP }} << 'EOF_SERVER_OPS'
            cd /home/f4host

            if [ ! -d "SYSTEMF4HOST" ]; then
              git clone git@github.com:${{ secrets.USERNAME_GITHUB }}/${{ secrets.NAME_REPO }}.git SYSTEMF4HOST
            fi

            cd SYSTEMF4HOST

            git fetch origin main
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            echo 'Git pull completed on server.'

            source /home/f4host/nodevenv/SYSTEMF4HOST/20/bin/activate
            echo 'Node.js virtual environment activated.'

            npm install --legacy-peer-deps || true
            echo 'Frontend dependencies installed on server.'

            npm run build
            echo 'Frontend assets built on server.'

            chmod -R 775 storage bootstrap/cache
            echo 'Permissions set completed on server.'

            php artisan storage:link
            echo 'Laravel storage:link executed on SYSTEMF4HOST/public.'

            rsync -avz --delete \
              --exclude 'index.php' \
              /home/f4host/SYSTEMF4HOST/public/ \
              /home/f4host/public_html/
            echo 'Public folder synced from SYSTEMF4HOST to public_html.'
            cat > /home/f4host/public_html/index.php << 'END'
          <?php

          use Illuminate\Foundation\Application;
          use Illuminate\Http\Request;

          define('LARAVEL_START', microtime(true));

          if (file_exists($maintenance = __DIR__.'/../SYSTEMF4HOST/storage/framework/maintenance.php')) {
              require $maintenance;
          }

          require __DIR__.'/../SYSTEMF4HOST/vendor/autoload.php';

          $app = require_once __DIR__.'/../SYSTEMF4HOST/bootstrap/app.php';

          $app->handleRequest(Request::capture());
          END
            echo 'Custom index.php created in public_html.'

            composer update
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear

            echo 'Laravel Artisan commands executed on server.'
          EOF_SERVER_OPS

          echo 'Deploy completed.'
