name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no smsbkk@${{ secrets.STAGING_SERVER_IP }} << 'EOF_SERVER_OPS'
            cd /home/smsbkk/repositories

            if [ ! -d "livescore-app" ]; then
              git clone git@github.com:${{ secrets.USERNAME_GITHUB }}/${{ secrets.NAME_REPO }}.git livescore-app
            fi

            cd livescore-app

            git fetch origin main
            git reset --hard origin/main
            git clean -fd
            echo 'Git updated on server.'

            # Backend
            composer install --no-dev --optimize-autoloader

            # Frontend
            npm install --legacy-peer-deps || true
            npm run build

            # Permissions
            chmod -R 775 storage bootstrap/cache
            php artisan storage:link

            # สร้าง symlink
            rm -rf /home/smsbkk/public_html
            ln -s /home/smsbkk/repositories/livescore-app/public /home/public/smsbkk/public_html

            # Artisan commands
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo 'Laravel optimized and deployed with symlink.'
          EOF_SERVER_OPS

          echo 'Deploy completed.'
